### ISSUE TITLE
算法如果单个规格数组超过36个会出错

### ISSUE THREAD

**Issue by 987674712** [kunjiang/cross-productor#1]
我看源码里写到了，比如 parseInt( 0, 40) 时会得到 NaN。。。。。

**Comment by kunjiang** [comment]
谢谢, 卓识不知道 parseInt 还有这个限制. 看样子需要重写这个算法.

**Comment by kunjiang** [comment]
原有算法中, 对于超出 10 进制的书都会有一些问题. 终归是在进制转换时有 bug. 重新实现 parseIntExt 后进行修复.
